spring:
  application:
    name: FACTURACION-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/udem_prueba_indukitchen?createDatabaseIfNotExist=true
    username: root
    password: root123.
  mail:
    host: smtp.office365.com
    port: 587
    username: trabajo.indukitchen2@hotmail.com
    password: Fundamentos123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8090
eureka:
  client:
    enabled: false
