server:
  port: 8081

spring:
  application:
    name: EJEMPLO-SERVICE
  datasource:
    url: jdbc:h2:file:~/facturacion-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost






